name: Pull Request Build and Test Library

on:
  pull_request:
    branches: [ main ]

  # Allow manual run
  workflow_dispatch:

jobs:
  BuildAndTest:
    strategy:
      matrix:
        options:
          - os: ubuntu-latest
            dotnetversion: 6.0.x
          - os: ubuntu-20.04
            dotnetversion: 6.0.x
          - os: macos-latest
            dotnetversion: 6.0.x
          - os: windows-latest
            dotnetversion: 6.0.x

    runs-on: ${{matrix.options.os}}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.options.dotnetversion}}
        include-prerelease: false

    - name: Install Obfuscar
      run: dotnet tool install --global Obfuscar.GlobalTool --version 2.2.32

    - name: Dotnet Release Build for Test
      run: dotnet build --verbosity normal --configuration Release

    - name: Run Unit Tests
      uses: b3b00/coverlet-action@1.1.7
      with:
        testProject: './Tests/Coderanger.ImageInfo.Tests.csproj'
        outputFormat: 'opencover'
        output: TestResults/coverage.opencover.xml
        threshold: 80
